### ISSUE TITLE
Problem on Heroku Only

### ISSUE THREAD

**Issue by akitaonrails** [Codeminer42/nlg_service#1]
I am loading a dependency Jar from `config/initializers/simple_nlg.rb` and from `app/models/simple_nlg.rb` I am `include_package`ing the Java classes.

From my development machine using OpenJDK 1.8 with JRuby 9.1.5.0 it load perfectly with Rails 4.2, both in development and production modes.

But only when I deploy to Heroku, which is using the same JDK and JRuby versions, it crashes with this error:

```
2016-10-25T23:29:30.944664+00:00 app[web.1]: NameError (XMLRealiser not found in packages simplenlg.aggregation, simplenlg.features, simplenlg.format.english, simplenlg.framework, simplenlg.lexicon, simplenlg.morphology.english, simplenlg.orthography.english, simplenlg.phrasespec, simplenlg.realiser.english, simplenlg.syntax.english, simplenlg.xmlrealiser, simplenlg.xmlrealiser.wrapper; last error: cannot load Java class simplenlg.xmlrealiser.wrapper.XMLRealiser):
2016-10-25T23:29:30.944665+00:00 app[web.1]:   app/controllers/api/realisers_controller.rb:7:in `create'
```

Which doesn't make any sense. If I load a `heroku run rails console` I see the same error trying to call `Java::SimplenlgXmlrealiser::XMLRealiser`:

```
irb(main):020:0> Java::SimplenlgXmlrealiser::XMLRealiser
NameError: missing class name (`simplenlg.xml.realiser.XMLRealiser')
	from org/jruby/javasupport/JavaPackage.java:128:in `const_missing'
```

The same thing in my development console returns correctly:

```
2.3.1 (main):0 > Java::SimplenlgXmlrealiser::XMLRealiser
=> Java::SimplenlgXmlrealiser::XMLRealiser
```

**Comment by headius** [comment]
Do you get a backtrace? This is like no error I've ever seen!

**Comment by akitaonrails** [comment]
I tried to force back to jruby 9.1.4.0 but still no luck.

This is the new deployment log:

```
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.3.1-jruby-9.1.4.0
remote: -----> Installing JVM: openjdk-8
remote: -----> Installing dependencies using bundler 1.11.2
remote:        Ruby version change detected. Clearing bundler cache.
remote:        Old: jruby 9.1.5.0 (2.3.1) 2016-09-07 fffffff OpenJDK 64-Bit Server VM 25.102-b14 on 1.8.0_102-cedar14-b14 +jit [linux-x86_64]
remote:        New: jruby 9.1.4.0 (2.3.1) 2016-09-02 fffffff OpenJDK 64-Bit Server VM 25.102-b14 on 1.8.0_102-cedar14-b14 +jit [linux-x86_64]
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching gem metadata from https://rubygems.org/...........
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Using json 1.8.3
remote:        Installing i18n 0.7.0
remote:        Installing minitest 5.9.1
remote:        Installing rake 11.3.0
remote:        Installing thread_safe 0.3.5
remote:        Installing builder 3.2.2
remote:        Installing erubis 2.7.0
remote:        Installing rack 1.6.4
remote:        Installing mime-types-data 3.2016.0521
remote:        Installing arel 6.0.3
remote:        Installing nokogiri 1.6.8.1
remote:        Installing concurrent-ruby 1.0.2
remote:        Installing dalli 2.7.6
remote:        Using jruby-openssl 0.9.17
remote:        Installing puma 3.6.0
remote:        Using bundler 1.11.2
remote:        Installing thor 0.19.1
remote:        Installing rails_serve_static_assets 0.0.5
remote:        Installing rails_stdout_logging 0.0.5
remote:        Installing tzinfo 1.2.2
remote:        Installing rack-test 0.6.3
remote:        Installing rack-attack 5.0.1
remote:        Installing rack-cache 1.6.1
remote:        Installing mime-types 3.1
remote:        Installing sprockets 3.7.0
remote:        Installing rails_12factor 0.0.3
remote:        Installing activesupport 4.2.7.1
remote:        Installing mail 2.6.4
remote:        Installing loofah 2.0.3
remote:        Installing rails-html-sanitizer 1.0.3
remote:        Installing globalid 0.3.7
remote:        Installing activemodel 4.2.7.1
remote:        Installing rails-deprecated_sanitizer 1.0.3
remote:        Installing activejob 4.2.7.1
remote:        Installing rails-dom-testing 1.0.7
remote:        Installing activerecord 4.2.7.1
remote:        Installing actionview 4.2.7.1
remote:        Installing actionpack 4.2.7.1
remote:        Installing actionmailer 4.2.7.1
remote:        Installing sprockets-rails 3.2.0
remote:        Installing railties 4.2.7.1
remote:        Installing rails-api 0.4.0
remote:        Installing rails 4.2.7.1
remote:        Bundle complete! 10 Gemfile dependencies, 43 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (33.44s)
remote:        Cleaning up the bundler cache.
remote:        Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:
remote: -----> Discovering process types
remote:        Procfile declares types     -> web
remote:        Default types for buildpack -> console, rake, worker
remote:
remote: -----> Compressing...
remote:        Done: 89.5M
remote: -----> Launching...
remote:        Released v15
remote:        https://nlg-service.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
```

And this is the result of trying to load the `SimpleNLG::XMLRealiser` which should be loaded from the Java `simplenlg.xmlrealiser.XMLRealiser` by `include_package`. Opening a remote console still errors out even trying to load it directly with `Java::SimplenlgXmlrealiser::XMLRealiser`:

```
2016-10-26T11:25:16.001353+00:00 app[web.1]: NameError (XMLRealiser not found in packages simplenlg.aggregation, simplenlg.features, simplenlg.format.english, simplenlg.framework, simplenlg.lexicon, simplenlg.morphology.english, simplenlg.orthography.english, simplenlg.phrasespec, simplenlg.realiser.english, simplenlg.syntax.english, simplenlg.xmlrealiser, simplenlg.xmlrealiser.wrapper; last error: cannot load Java class simplenlg.xmlrealiser.wrapper.XMLRealiser):
2016-10-26T11:25:16.001358+00:00 app[web.1]:   app/controllers/api/realisers_controller.rb:7:in `create'
```

cc @headius

**Comment by hannelita** [comment]
Hi, it looks like this JAR has some local dependencies on its pom.xml: 

```xml
<dependency>
    <groupId>gov.nih.nlm.nls.lexAccess.Api</groupId>
    <artifactId>LexAccess2011dist</artifactId>
    <version>0.0.1</version>
    <scope>system</scope>
    <systemPath>${basedir}/lib/lexAccess2011dist.jar</systemPath>
 </dependency>
```
(source:  https://github.com/simplenlg/simplenlg/blob/master/pom.xml)

So you might need to manually add this JAR on your classpath when deploying to Heroku. Otherwise, it might not work properly.

There is also an explicit task described on the pom.xml. It unzips and runs a file. It might also interfere on the process.

**Comment by akitaonrails** [comment]
Figured it out, the culprit is git LFS. I had it tracking jar files.

Heroku does not support LFS and it usually not even let a git push. But it let it that time.

And the .jar file was corrupted in the deployment, which is why it was not finding any class.

@headius only thing is that the error message said (correctly) that it couldn't find the class but it didn't mention any hints that the jar was actually corrupted.
